### ISSUE TITLE
Error loading keys

### ISSUE THREAD

**Issue by CamxxCore** [bitpay/wallet#11432]
Suddenly I cannot access my wallets on Copay.  Trying to load the app is met with the following error. Please help :( https://i.imgur.com/MFE5O76.png

**Comment by CamxxCore** [comment]
This happened immediately after creating a new multi- sig wallet and transferring roughly 20,000 USD worth of bitcoin. now I have no access to the wallets, the private keys, or any kind of backup due to this error. I had no time to even create any backups because this error now appears every time I launch the app. how do I get my money back???

**Comment by maektwain** [comment]
Seems like your keys or storage went null, did you download the binary from PlayStore ? did you compile it?

There is n way for you to recover your keys , since you cannot access the storage directly..

**Comment by maektwain** [comment]
Maybe you used the fake version , of the app there is this fake copay app on the PlayStore

**Comment by CamxxCore** [comment]
I am using iOS, but thank god I managed to recover my wallets by importing my mnemonic to the official bitpay app. I was lucky, beware to users of the copay app, I would suggest switching to the official app as soon as possible.
