### ISSUE TITLE
Clone of your app is on google play market

### ISSUE THREAD

**Issue by Undeadlol1** [bitpay/wallet#11482]
FYI this app is on google play market is most likely not legit.

https://play.google.com/store/apps/details?id=com.walletc.opay

I reported it through mobile version of google play market but not sure if it is going to be taken down.

**Comment by cmgustavo** [comment]
It's not legit app. Copay official app is not available on PlayStore any more. Checkout official BitPay App here: https://play.google.com/store/apps/details?id=com.bitpay.wallet 

Thanks for reporting.

**Comment by mrbaguvix** [comment]
![Screen Shot 2021-05-30 at 4 14 48 AM](https://user-images.githubusercontent.com/3173957/120090841-968cc980-c0fd-11eb-89c4-2797a334597c.png)
I think the reported clone has been taken down. Can we mark this issue as resolved now? @Undeadlol1

**Comment by Undeadlol1** [comment]
Thank you.
