### ISSUE TITLE
 Allow snap "bitpay" to change "default-url-scheme-handler" subproperty "bitcoin" to "bitpay_bitpay.desktop" every time upon startup

### ISSUE THREAD

**Issue by NateNate60** [bitpay/wallet#11486]
This isn't inhibiting use, but it's rather annoying to have to answer "yes" to the following prompts every time I start up Bitpay Wallet.

System information:

* Ubuntu 20.04 LTS
* Ryzen 5 2600
* GTX 1070 Ti, latest NVIDIA drivers
* Bitpay Wallet 11.2.13

Once I start up Bitpay Wallet after installing it, I'm prompted with this message:

![image](https://user-images.githubusercontent.com/41277019/107289854-7c2dc380-6a1a-11eb-95f6-6b0b7d5b19e5.png)

...and then this one:

![image](https://user-images.githubusercontent.com/41277019/107289903-8e0f6680-6a1a-11eb-951e-a396bff53b68.png)

...and several more.

Setting the properties manually using the terminal and `xdg-settings` does not stop the prompts.

    nathan@Sapphire-Desktop:~$ xdg-settings set default-url-scheme-handler bitcoincash bitpay_bitpay.desktop

I'm guessing that the program is simply trying to set the settings every single time on startup, rather than only the first time.

**Comment by aahnik** [comment]
I am also facing the same issue. It is very annoying to answer the 5 prompts every time I open bitpay. Just destroys the experience of using it.

**Comment by aahnik** [comment]
This issue is just killing experience. How to fix it ? please help. I have to make five clicks before the app opens.

I have tried uninstalling and reinstalling the app. But nothing helps.

@cmgustavo @matiu

**Comment by NateNate60** [comment]
> This issue is just killing experience. How to fix it ? please help. I have to make five clicks before the app opens.
> 
> I have tried uninstalling and reinstalling the app. But nothing helps.
> 
> @cmgustavo @matiu

I'm guessing it's a low-priority issue since it doesn't inhibit use. The last time I submitted an issue, they fixed it within 24 hours, but that's probably only because it was completely preventing people from spending BCH from the wallet.

**Comment by pegranka** [comment]
Same issue for Copay version 12.3.2 running as a snap on ubuntu 12.04. Makes Copay very annoying to use.

**Comment by gabrielbazan7** [comment]
https://github.com/bitpay/wallet/pull/11630

**Comment by aahnik** [comment]
hi @gabrielbazan7 and @cmgustavo 

this is not yet solved. i uninstalled bitpay and reinstalled (I hope that gives latest version)

``` shell
sudo snap remove bitpay
sudo snap install bitpay
```

My current version
```shell
Desktop: BitPay v12.4.4
```

**Comment by cmgustavo** [comment]
Sorry about this issue. We hope it's fixed in the next release.
