### ISSUE TITLE
Source code of latest version on Google Play 14.7.4 is not available

### ISSUE THREAD

**Issue by Giszmo** [bitpay/wallet#12065]
**Describe the bug**

The latest version on Google Play is newer than the latest commit on GitHub.
Please publish all the code and please also document how to reproduce the binaries using containers #11748

**Comment by emanuelb** [comment]
Issue can be closed as code for version 14.7.4 is published in another repo: https://github.com/bitpay/bitpay-app/releases/tag/v.14.7.4
and there is tag for the version currently on google play 14.8.2 as well https://github.com/bitpay/bitpay-app/releases/tag/v.14.8.2
