### ISSUE TITLE
Any leads to my btc??

### ISSUE THREAD

**Issue by Densequera** [bitpay/wallet#12140]
Hello I purchased bitcoins from glidera and quite find it on Bitpay. How can I use them on copay or Bitpay somehow here is my info there were 3 seperate transactions on different days.

Date: 1/21/16
Bitcoin address: 1HMFHhVL3ES3kwvkkwwyMpPy7yazYpf5pH
฿0.03616

Date: 1/19/16
Bitcoin address: 18jns8aAE94BZWsu59Gvb73nEB7ECV3tSp
฿0.0664

Date: 12/9/15
Bitcoin address: 1G1msqn4qpkcvYZPZ7GxrUQg8gCqs2akiD
฿0.06038

The 12/9/15 been looking for leads to these bitcoins. With any personal information from myself can I get leads to where or what I did with these bitcoins? Was new to it back then.

**Comment by Densequera** [comment]
Thanks

**Comment by Gamboster** [comment]
@Densequera Please do not follow this user's instructions (Tony-ptech). He is probably trying to scam you. This repository is deprecated, please raise your questions or complaints to the current wallet repository (https://github.com/bitpay/bitpay-app/issues) or to one of the official bitpay channels: https://support.bitpay.com/hc/en-us
