### ISSUE TITLE
Getting profile pictures from gravatar

### ISSUE THREAD

**Issue by JackScottie** [bitpay/wallet#1749]
I like the new profile feature of copay.  I noticed the default profile picture by my email address, but no way of uploading or selecting a picture.  Since we are logging in with an email address as the username, it is really easy to grab a profile picture from gravatar.  https://en.gravatar.com/site/implement/images/

**Comment by monsterbitar** [comment]
Sorry for poking in an old closed thread, but is there anyway to set a profile image on participants when not logging in to the website, but rather using the android app?

**Comment by dabura667** [comment]
umm... Copay changed from a "log in" type service to "keys are stored locally, so no login is necessary" model a long time ago.
