### ISSUE TITLE
Wish would be easier to create 2nd, 3rd accounts from same seed

### ISSUE THREAD

**Issue by avibrazil** [bitpay/wallet#3735]
It is currently too difficult to create an m/44/x/1, m/44/x/2 m/44/x/3 etc wallets.
A seed input and manual derivation configuration is needed to achieve this in a non-intuitive "Create Wallet" operation.

Mycelium, on the other hand, makes this task easier with a single tap on "+" and add a human name as "Account 2".

Thank you

**Comment by XBTdev** [comment]
+1

**Comment by matiu** [comment]
Related https://github.com/bitpay/copay/issues/3236#issuecomment-152979128

**Comment by JDonadio** [comment]
Related https://github.com/bitpay/copay/issues/4760

**Comment by rgime** [comment]
> It is currently too difficult to create an m/44/x/1, m/44/x/2 m/44/x/3 etc wallets.
> A seed input and manual derivation configuration is needed to achieve this in a non-intuitive "Create Wallet" operation.
> 
> Mycelium, on the other hand, makes this task easier with a single tap on "+" and add a human name as "Account 2".
> 
> Thank you

Yes, was looking for the sabe thing. Any suggestion ? Could found a way to do this ? @avibrazil

**Comment by avibrazil** [comment]
> Yes, was looking for the sabe thing. Any suggestion ? Could found a way to do this ? @avibrazil

Coinoim wallet operates exactly this way and I switched to it a long time ago.
Coinomi also supports SegWit, more coins and is much more powerful.

**Comment by matiu** [comment]
Adding new wallets to a seed is now supported, it is actually the default behavior; segwit is also supported and native segwit wallets are the default for BTC.
