### ISSUE TITLE
Old phone died can't import funds to new phone

### ISSUE THREAD

**Issue by InigoMontpiya** [bitpay/wallet#8438]
My old phone died and I have just got my hands on a new one. I was not worried about my copay wallet as I had my pass words written down.

I got the app on my new phone opened it and chose the restore option. It all went without a hitch expect my funds have not come through.

Please help

**Comment by Gamboster** [comment]
Hello @InigoMontpiya 
Could you provide me the wallet id of the wallet that you import into your new cell phone? So I can review. Thank you
Go to Settings -> Your wallet -> More options -> Wallet information -> wallet id

**Comment by InigoMontpiya** [comment]
Hi @Gamboster,

Wallet I'd on new phone is 

bcd73ee5-7530-415c-854f-ec18e08cbfe2

No issues with import but doesn't seem to pick up old addresses or funds.

**Comment by InigoMontpiya** [comment]
The address I cannot seem to access is 

1MsJm3Yi7LG2wqojXSwDcynYNNRiBz4vF8

**Comment by InigoMontpiya** [comment]
@Gamboster,

Any update?

**Comment by gabrielbazan7** [comment]
Duplicated https://github.com/bitpay/copay/issues/8458
