### ISSUE TITLE
Bitcoin not received in recipient account

### ISSUE THREAD

**Issue by kktc03** [bitpay/wallet#8537]
Hi there,
I have sent 0.1 bitcoin to bitoasis through copay wallet from ios device. Even after 11 confirmations its not arrived in the recipients account. Please refer the transaction id below.

cb1441f8a9b0265179ab9cce5433deb4d3ec1c7dbc2cfc11bfd01e9b9369be15

Please update. Thanks

kk

**Comment by BGalliotti** [comment]
Hello @kktc03  as we could see, your transaction has currently 18 confirmations. 
The transaction is already done and confirmed, nothing is wrong with the sender wallet.
You should check on the recipient end.

If we can further help, let us know
Regards

**Comment by Dawood66** [comment]
Hi there,
I have sent 0.219213  bitcoin to another BTC Address .  

It  has  Not been received at this address 

 Please refer the transaction id below.

8c34826e4bc86e78aa850fa9aeb48b1a88fb84ed13455d4bf3c1d5d9e45aad2c

**Comment by BGalliotti** [comment]
Hello @Dawood66 ,

The transaction has been sent and the funds are already spent:

https://bit.ly/2jKHQ5E

**(S): Spent**
**(U): Unspent**

Feel free to get back to us in case you have any questions or concerns.
Thank you for your interest and support.

**Comment by Dawood66** [comment]
Hi, sorry but i have checked my account and money has not been received. Dawood Harnekar
