### ISSUE TITLE
Encrypt passwords being saved

### ISSUE THREAD

**Issue by Nodja** [bitpay/wallet#8545]
Bitpay seems to be have at some point be remembering the encryption passwords.

I only noticed because in 4.2.0 under the add funds to card this showed up.

![image](https://user-images.githubusercontent.com/7379193/39554446-da5ac852-4e40-11e8-9503-6d4583130e27.png)

This is a serious issue as passwords can be easily recovered, I've used [this](https://github.com/byt3bl33d3r/chrome-decrypter) python script and the passwords are correct. You can pass it "%localappdata%\bitpay\User Data\Default\Login Data" as an argument (make sure bitpay is closed).

As a manual workaround you can delete the Login Data files under bitpay's chrome profile directory.

I recommend bitpay manually clear the login data on startup.

**Comment by BGalliotti** [comment]
Thanks @Nodja for your contribution.

Our development team is checking this issue out.

Best regards.

**Comment by BGalliotti** [comment]
For the mac version you can try this command:

rm ~/Library/Application Support/YOURAPPNAME/Default/Login Data/* and try again
For more comments on this, please follow  #5184
