### ISSUE TITLE
iOS BTC Testnet does not generate new addresses - Single address wallet

### ISSUE THREAD

**Issue by alekplay** [bitpay/wallet#9119]
I'm currently using Copay as a BTC testnet wallet on my iOS device. I've noticed that every time I enter the *Receive* tab, I am presented with the same address. This address persists through relaunches, and even when pressing the refresh button. 

Probably related, I also noticed that sometimes the address is duplicated (i.e. the end of the address is appended with the same address). To fix this I can simply press the refresh button, but its an annoying bug nonetheless. Please see attached screenshot: [http://oi63.tinypic.com/23igp4w.jpg](http://oi63.tinypic.com/23igp4w.jpg).

This has been the default behavior for me since downloading the app. BCH testnet seems to work fine without any of these issues.

**Comment by alekplay** [comment]
@BGalliotti perhaps perhaps I was not clear enough in the original issue description, but allow me to elaborate by answering your points.

> _When you tap send, the wallet generates a new address_
I have sent multiple times from my Copay BTC Testnet wallet, yet the address has never changed. 

> _[...] You will get the same [across relaunches] unless you tap the refresh button_
Tapping the refresh button does not yield a new address, the address stays the same.

> _If you [send funds to an address], the next time you go to the *Receive* screen, you will get a new address_
I have sent funds to my wallet *12 times*, yet only ever been presented with the same address. In fact, that's what prompted my discovery of this issue as every time I went to receive coins from a faucet I was blocked for using the same address multiple times as that's what Copay generated

Furthermore, this did not answer the bug of seeing duplicated addresses as shown in the attached picture. Perhaps you'd like me to create a separate issue for that, although I believe the issues to be linked.

**Comment by BGalliotti** [comment]
Hello @alekplay 
Thanks for reaching out to us.

> I have sent multiple times from my Copay BTC Testnet wallet, yet the address has never changed.

Have you created a **Single address** wallet?
If you open the wallet and it says **AUDITABLE** on the left lower corner of the "header" (see attachment)

> Furthermore, this did not answer the bug of seeing duplicated addresses as shown in the attached picture. Perhaps you'd like me to create a separate issue for that, although I believe the issues to be linked.

Thanks for pointing this out. This is an issue we are aware of, it shows the same address concatenated two times, this happens rarely, so far we have experienced it very few times and did not find a pattern.

You can open a new issue for that specific case so the community can contribute and help us with the resolution.
![screenshot_20180914-150131](https://user-images.githubusercontent.com/38531900/45567267-aff76580-b82f-11e8-94c2-3b7217381964.png)

Please let us know if you have any additional questions.
Kind regards.

**Comment by alekplay** [comment]
@BGalliotti it does indeed say **Auditable**. I was not aware of this option or its significance. How do I turn that off?

Furthermore, I will go ahead and create a separate issue for the duplicate/ concatenated addresses.

**Comment by BGalliotti** [comment]
Hello @alekplay 
Thanks for reaching out to us.

> How do I turn that off? 

You cannot turn this feature off. This is something you have set up when creating the wallet, but cannot be changed. You should move your funds to another wallet in case you want to use them on a regular wallet.

> Furthermore, I will go ahead and create a separate issue for the duplicate/ concatenated addresses.

Excellent! thanks for your contribution.

Please let us know if you have any additional questions.
Kind regards.
