### ISSUE TITLE
Contraseña incorrecta

### ISSUE THREAD

**Issue by Francomoray** [bitpay/wallet#9426]
Hola, recién quise enviar un pago y me al colocar mi contraseña de cifrado me dice que es incorrecta y de ninguna manera esto puede ser posible ya que siempre estoy enviando con la misma contraseña y ahora me dice que es incorrecta, me podrían ayudar por favor?

**Comment by BGalliotti** [comment]
Hola @Francomoray 
Gracias por ponerse en contacto con nosotros.

Si usted estar usando la contraseña frecuentemente, por favor asegúrese de estar ingresandola correctamente.

Si el error persiste, por favor envíenos un captura de pantalla del error y la version de la aplicación y del sistema operativo de su dispositivo.

Por favor, háganos saber si tiene alguna pregunta adicional.
Saludos cordiales.

**Comment by Francomoray** [comment]
![screenshot_20181226-221422](https://user-images.githubusercontent.com/46167507/50461242-d1eaa300-095b-11e9-911f-75d6edfce96b.png)

Ese es el mensaje de error que me da la aplicación, encontré un archivo donde yo guardé mi contraseña por si algún día me olvidaba y es exactamente la misma que uso siempre, sólo lo hice para asegurarme de estar poniéndola correctamente, reinicié el teléfono y tampoco se solucionó el problema, no se si será porque hace poco actualice el android aunque no creo que a eso se pueda deber el problema, mi versión de android es la 7.0 y la versión de Bitpay es la última descargada desde el playstore, desafortunadamente sólo tengo anotada la contraseña y no tengo anotadas las 12 palabras, sencillamente no le di importancia porque es bastante difícil que me olvide mi contraseña, nunca esperé enfrentarme a un error como este, definitivamente estoy poniendo mi contraseña correctamente y el error persiste, si pueden ayudarme les agradeceré, hoy hice el deposito en mi wallet de bitpay para pasarlos a mi broker de forex y ahora tengo congelados mis fondos, mi dinero que me costó mucho juntar

**Comment by BGalliotti** [comment]
Hola @Francomoray 
Gracias por ponerse en contacto con nosotros.

Lo que plantea es en principio imposible.

Debe estar ingresando una contraseña incorrecta o quizas la contraseña pertenece a otra billetera.
Tenga en cuenta que la aplicación diferencia mayúsculas, minúsculas, 

Lamentablemente si no tiene las doce palabras, no le queda otra alternativa que recordar la contraseña.

Por favor, háganos saber si tiene alguna pregunta adicional.
Saludos cordiales.

**Comment by BGalliotti** [comment]
Hola @Francomoray 

Realmente lamentamos la experiencia que tuvo.

De acuerdo con nuestro equipo de desarrollo, la aplicación está funcionando correctamente y no hay fallas en el sistema de contraseñas.

> la próxima vez voy a anotar las palabras que son mas importantes que la contraseña
Excelente, se lo recomendamos totalmente

Por favor, háganos saber si tiene alguna pregunta adicional.
Saludos cordiales.
