### ISSUE TITLE
Open in Wallet does not work for BCH testnet

### ISSUE THREAD

**Issue by way2rach** [bitpay/wallet#9557]
Copy payment URL would open a testnet innvoice, but Open in Wallet does not. Steps to reproduce:

1) Go to test.bitpay.com. Create a test invoice, click `Open in Wallet`. The Copay app will open, but the transaction details won't show up. 

If the app is already open, the button works fine. But if the app is not already running, nothing happens. Tested on iOS 12.1.4

**Comment by BGalliotti** [comment]
Hello @way2rach 
Thanks for your feedback, we apologize for the inconveniences this may have caused.

We are researching this issue and will post back as soon as possible.

Please let us know if you have any additional questions.
Kind regards.

**Comment by way2rach** [comment]
obsolete
